# Generated by Django 4.1.4 on 2023-01-10 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CviewServicesMaster',
            fields=[
                ('cv_service_id', models.AutoField(db_column='CV_Service_ID', primary_key=True, serialize=False)),
                ('cv_service_name', models.CharField(db_column='Cv_Service_Name', max_length=45)),
                ('cv_service_description', models.CharField(blank=True, db_column='Cv_Service_Description', max_length=45, null=True)),
            ],
            options={
                'db_table': 'cview_services_master',
            },
        ),
        migrations.CreateModel(
            name='TblRoleMaster',
            fields=[
                ('role_id', models.AutoField(db_column='Role_ID', primary_key=True, serialize=False)),
                ('role_description', models.CharField(db_column='Role_Description', max_length=45)),
                ('role_assign_screenids', models.CharField(blank=True, db_column='Role_Assign_ScreenIDs', max_length=45, null=True)),
            ],
            options={
                'db_table': 'tbl_role_master',
            },
        ),
        migrations.CreateModel(
            name='TblUserMaster',
            fields=[
                ('user_id', models.AutoField(db_column='User_Id', primary_key=True, serialize=False)),
                ('user_type', models.CharField(db_column='User_Type', max_length=45)),
                ('user_last_name', models.CharField(db_column='User_Last_Name', max_length=45)),
                ('user_first_name', models.CharField(blank=True, db_column='User_First_Name', max_length=45, null=True)),
                ('user_middle_name', models.CharField(blank=True, db_column='User_Middle_Name', max_length=45, null=True)),
                ('user_email', models.CharField(db_column='User_eMail', max_length=45)),
                ('user_mobile_number', models.IntegerField(db_column='User_Mobile_Number')),
                ('user_alternative_number', models.IntegerField(blank=True, db_column='User_Alternative_Number', null=True)),
                ('user_role', models.ForeignKey(db_column='User_Role', on_delete=django.db.models.deletion.DO_NOTHING, to='cview.tblrolemaster')),
            ],
            options={
                'db_table': 'tbl_user_master',
            },
        ),
        migrations.CreateModel(
            name='UserTechSkills',
            fields=[
                ('tech_skills_id', models.AutoField(db_column='Tech_Skills_ID', primary_key=True, serialize=False)),
                ('tech_skill_description', models.TextField(blank=True, db_column='Tech_Skill_Description', null=True)),
                ('user', models.ForeignKey(db_column='User_Id', on_delete=django.db.models.deletion.DO_NOTHING, to='cview.tblusermaster')),
            ],
            options={
                'db_table': 'user_tech_skills',
            },
        ),
        migrations.CreateModel(
            name='TblUserProjects',
            fields=[
                ('user_project_id', models.AutoField(db_column='User_Project_ID', primary_key=True, serialize=False)),
                ('user_project_title', models.CharField(blank=True, db_column='User_Project_Title', max_length=45, null=True)),
                ('user_role_responsibilities', models.TextField(blank=True, db_column='User_Role_Responsibilities', null=True)),
                ('user_technology_used', models.CharField(blank=True, db_column='User_Technology_Used', max_length=45, null=True)),
                ('user_project_description', models.TextField(blank=True, db_column='User_Project_Description', null=True)),
                ('tbl_user_projectscol', models.CharField(blank=True, db_column='Tbl_User_Projectscol', max_length=45, null=True)),
                ('user', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cview.tblusermaster')),
            ],
            options={
                'db_table': 'tbl_user_projects',
            },
        ),
        migrations.CreateModel(
            name='TblUserProf',
            fields=[
                ('user_prof_id', models.AutoField(db_column='User_Prof_Id', primary_key=True, serialize=False)),
                ('user_prof_summary', models.TextField(blank=True, db_column='User_Prof_summary', null=True)),
                ('tbl_user_profcol', models.CharField(blank=True, db_column='Tbl_User_Profcol', max_length=45, null=True)),
                ('user', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cview.tblusermaster')),
            ],
            options={
                'db_table': 'tbl_user_prof',
            },
        ),
        migrations.CreateModel(
            name='TblUserExperience',
            fields=[
                ('user_exp_id', models.AutoField(db_column='User_Exp_ID', primary_key=True, serialize=False)),
                ('user_work_exp_company', models.CharField(blank=True, db_column='User_Work_Exp_Company', max_length=45, null=True)),
                ('user_work_exp_disignation', models.CharField(blank=True, db_column='User_Work_Exp_Disignation', max_length=45, null=True)),
                ('user_work_exp_from_date', models.DateField(blank=True, db_column='User_Work_Exp_From_Date', null=True)),
                ('user_work_exp_to_date', models.DateField(blank=True, db_column='User_Work_Exp_To_Date', null=True)),
                ('user', models.ForeignKey(db_column='User_Id', on_delete=django.db.models.deletion.DO_NOTHING, to='cview.tblusermaster')),
            ],
            options={
                'db_table': 'tbl_user_experience',
            },
        ),
        migrations.CreateModel(
            name='TblUserEducation',
            fields=[
                ('education_id', models.AutoField(db_column='Education_Id', primary_key=True, serialize=False)),
                ('user_education', models.CharField(db_column='User_Education', max_length=45)),
                ('user_education_inistitute_name', models.CharField(db_column='User_Education_Inistitute_Name', max_length=45)),
                ('user_educatin_inistitute_city', models.CharField(db_column='User_Educatin_Inistitute_City', max_length=45)),
                ('user_educatin_inistitute_country', models.CharField(db_column='User_Educatin_Inistitute_Country', max_length=45)),
                ('user_education_grade_percentage', models.CharField(db_column='User_Education_Grade_Percentage', max_length=4)),
                ('user_education_passout_start_date', models.DateField(db_column='User_Education_Passout_Start_Date')),
                ('user_education_passout_end_year', models.DateField(blank=True, db_column='User_Education_Passout_End_Year', null=True)),
                ('user', models.ForeignKey(db_column='User_Id', on_delete=django.db.models.deletion.DO_NOTHING, to='cview.tblusermaster')),
            ],
            options={
                'db_table': 'tbl_user_education',
            },
        ),
        migrations.CreateModel(
            name='TblUserActivities',
            fields=[
                ('user_activity_id', models.AutoField(db_column='User_Activity_Id', primary_key=True, serialize=False)),
                ('user_activity_name', models.CharField(blank=True, db_column='User_Activity_name', max_length=45, null=True)),
                ('user_activity_description', models.TextField(blank=True, db_column='User_Activity_Description', null=True)),
                ('user_awards', models.TextField(blank=True, db_column='User_Awards', null=True)),
                ('user_papers_submitted', models.TextField(blank=True, db_column='User_Papers_Submitted', null=True)),
                ('user_anyother_information', models.TextField(blank=True, db_column='User_AnyOther_Information', null=True)),
                ('user', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cview.tblusermaster')),
            ],
            options={
                'db_table': 'tbl_user_activities',
            },
        ),
        migrations.CreateModel(
            name='TblCviewSubServices',
            fields=[
                ('cv_sub_service_id', models.AutoField(db_column='Cv_Sub_Service_ID', primary_key=True, serialize=False)),
                ('cv_sub_service_descrtiption', models.CharField(blank=True, db_column='Cv_Sub_Service_Descrtiption', max_length=45, null=True)),
                ('cv_sub_service_location', models.CharField(blank=True, db_column='Cv_Sub_Service_Location', max_length=45, null=True)),
                ('cv_service', models.ForeignKey(db_column='Cv_Service_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cview.cviewservicesmaster')),
            ],
            options={
                'db_table': 'tbl_cview_sub_services',
            },
        ),
    ]
